BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `ZADANIA` (
	`ID_ZADANIA`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_ZADANIA`	TEXT NOT NULL UNIQUE,
	`STATUS`	INTEGER NOT NULL,
	`PRIORYTET`	TEXT NOT NULL,
	`ID_ZGLASZAJACEGO`	INTEGER NOT NULL,
	`ID_PRZYPISANEGO`	INTEGER NOT NULL,
	`DATA_UTWORZENIA`	TEXT NOT NULL,
	`DATA_AKTUALIZACJI`	TEXT NOT NULL,
	`OPIS`	TEXT NOT NULL,
	`KOMENTARZ`	TEXT,
	`ID_PROJEKTU`	INTEGER NOT NULL,
	`ID_SPRINTU`	INTEGER NOT NULL,
	`ID_GRUPY`	INTEGER,
	FOREIGN KEY(`ID_GRUPY`) REFERENCES `GRUPY`(`ID_GRUPY`),
	FOREIGN KEY(`ID_ZGLASZAJACEGO`) REFERENCES `UZYTKOWNICY`(`ID_UZYTKOWNIKA`),
	FOREIGN KEY(`ID_PRZYPISANEGO`) REFERENCES `UZYTKOWNICY`(`ID_UZYTKOWNIKA`),
	FOREIGN KEY(`ID_SPRINTU`) REFERENCES `SPRINTY`(`ID_SPRINTU`),
	FOREIGN KEY(`ID_PROJEKTU`) REFERENCES `PROJEKTY`(`ID_PROJEKTU`)
);
CREATE TABLE IF NOT EXISTS `UZYTKOWNICY` (
	`ID_UZYTKOWNIKA`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`IMIE`	TEXT NOT NULL,
	`NAZWISKO`	TEXT NOT NULL,
	`ID_STANOWISKA`	INTEGER,
	`ID_GRUPY`	INTEGER,
	`ID_PROJEKTU`	INTEGER,
	`ID_FIRMY`	INTEGER NOT NULL,
	`LOGIN`	TEXT NOT NULL UNIQUE,
	`HASLO`	TEXT NOT NULL,
	FOREIGN KEY(`ID_PROJEKTU`) REFERENCES `PROJEKTY`(`ID_PROJEKTU`),
	FOREIGN KEY(`ID_GRUPY`) REFERENCES `GRUPY`(`ID_GRUPY`),
	FOREIGN KEY(`ID_FIRMY`) REFERENCES `FIRMY`(`ID_FIRMY`),
	FOREIGN KEY(`ID_STANOWISKA`) REFERENCES `STANOWISKA`(`ID_STANOWISKA`)
);
CREATE TABLE IF NOT EXISTS `STANOWISKA` (
	`ID_STANOWISKA`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_STANOWISKA`	TEXT NOT NULL UNIQUE,
	`OPIS_STANOWISKA`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `SPRINTY` (
	`ID_SPRINTU`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_SPRINTU`	TEXT NOT NULL,
	`DATA_START_SPRINTU`	TEXT NOT NULL,
	`DATA_END_SPRINTU`	TEXT NOT NULL,
	`OPIS_SPRINTU`	TEXT NOT NULL,
	`ID_PROJEKTU`	INTEGER,
	FOREIGN KEY(`ID_PROJEKTU`) REFERENCES `PROJEKTY`(`ID_PROJEKTU`)
);
CREATE TABLE IF NOT EXISTS `PROJEKTY` (
	`ID_PROJEKTU`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_PROJEKTU`	TEXT NOT NULL UNIQUE,
	`ID_FIRMY_ZLECAJACEJ`	INTEGER NOT NULL,
	`DATA_START`	TEXT NOT NULL,
	`DATA_END`	TEXT NOT NULL,
	`KOSZT_PROJEKTU`	INTEGER NOT NULL,
	`OPIS_PROJEKTU`	TEXT NOT NULL,
	`STATUS_PROJEKTU`	TEXT,
	`KOMENTARZ_ZLECAJACEGO`	TEXT,
	`ID_KIEROWNIKA`	INTEGER NOT NULL UNIQUE,
	FOREIGN KEY(`ID_FIRMY_ZLECAJACEJ`) REFERENCES `UZYTKOWNICY`(`ID_UZYTKOWNIKA`),
	FOREIGN KEY(`ID_KIEROWNIKA`) REFERENCES `UZYTKOWNICY`(`ID_UZYTKOWNIKA`)
);
CREATE TABLE IF NOT EXISTS `PRIORYTETY` (
	`ID_PRIORYTETU`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_PRIORYTETU`	TEXT NOT NULL UNIQUE,
	`OPIS`	TEXT
);
CREATE TABLE IF NOT EXISTS `GRUPY` (
	`ID_GRUPY`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_GRUPY`	TEXT NOT NULL UNIQUE,
	`ID_LIDERA`	INTEGER NOT NULL,
	`ID_PROJEKTU`	INTEGER NOT NULL,
	`OPIS_GRUPY`	TEXT NOT NULL,
	FOREIGN KEY(`ID_PROJEKTU`) REFERENCES `PROJEKTY`(`ID_PROJEKTU`),
	FOREIGN KEY(`ID_LIDERA`) REFERENCES `UZYTKOWNICY`(`ID_UZYTKOWNIKA`)
);
CREATE TABLE IF NOT EXISTS `FIRMY` (
	`ID_FIRMY`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`NAZWA_FIRMY`	TEXT NOT NULL UNIQUE,
	`ADRES_FIRMY`	TEXT NOT NULL,
	`OPIS_FIRMY`	TEXT NOT NULL,
	`EMAIL_FIRMY`	TEXT UNIQUE
);
CREATE TABLE IF NOT EXISTS `CHAT` (
	`ID_WIADOMOSCI`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`LOGIN`	TEXT NOT NULL,
	`TRESC`	TEXT NOT NULL,
	`DATA_WYSLANIA`	TEXT NOT NULL,
	`ID_PROJEKTU`	INTEGER NOT NULL,
	`ID_GRUPY`	INTEGER NOT NULL
);
COMMIT;
